### ISSUE TITLE
import HTML5Backend in HTML5toTouch breaks

### ISSUE THREAD

**Issue by Phinodel** [LouisBrunner/dnd-multi-backend#52]
I've made a quick game of questions where one uses a drag and drop to put the answers in the right order.
At first I made it just in `react-dnd` as I didn't need to support mobile.
Now mobile support has been requested as well as Desktop support I've tried implementing your library (which is a perfect solution for me btw, great work!)

So I've swapped out `react-dnd` for `react-dnd-multi-backend` by so:
```
// import { DndProvider } from 'react-dnd';
// import { HTML5Backend } from 'react-dnd-html5-backend';

import { DndProvider } from 'react-dnd-multi-backend';
import HTML5toTouch from 'react-dnd-multi-backend/dist/esm/HTML5toTouch';
```
...
```
<DndProvider options={HTML5toTouch}>...</DndProvider>
```

and on compiling I get the following error:

```
/.../node_modules/react-dnd-multi-backend/dist/esm/HTML5toTouch.js:1
import { HTML5Backend } from 'react-dnd-html5-backend';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module._compile (/.../node_modules/source-map-support/source-map-support.js:547:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.nodeDevHook [as .js] (/.../node_modules/ts-node-dev/lib/hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at eval (webpack-internal:///react-dnd-multi-backend/dist/esm/HTML5toTouch:1:18)
    at Object.react-dnd-multi-backend/dist/esm/HTML5toTouch (/.../src/.next/server/static/development/pages/game.js:2209:1)
    at __webpack_require__ (/.../src/.next/server/static/development/pages/game.js:23:31)
    at eval (webpack-internal:///./modules/game/components/Game.tsx:6:103)
    at Module../modules/game/components/Game.tsx (/.../src/.next/server/static/development/pages/game.js:1519:1)
    at __webpack_require__ (/.../src/.next/server/static/development/pages/game.js:23:31)
    at eval (webpack-internal:///./modules/game/index.tsx:6:74)
```

Package versions:
```
"react-dnd": "^11.1.3",
"react-dnd-html5-backend": "^11.1.3",
"react-dnd-multi-backend": "^6.0.2",
"react-dnd-touch-backend": "^11.1.3",
```

Node version local: 10.21.0
Node version in dev dependencies: `"@types/node": "^14.0.1",`

Project info:
made with Nextjs: ^9.4.1
react version: ^16.13.1

Typescript info:
```
"@typescript-eslint/eslint-plugin": "^2.34.0",
"@typescript-eslint/parser": "^2.34.0",
"eslint": "^7.0.0",
"ts-node-dev": "^1.0.0-pre.44",
"typescript": "^3.9.2"
```

**Comment by LouisBrunner** [comment]
Hi @Phinodel,

From a quick look, it looks like you need to use the CommonJS version of `HTML5toTouch`.
Thus your import should look like:
```
import HTML5toTouch from 'react-dnd-multi-backend/dist/cjs/HTML5toTouch';
```

Hopefully that solves the issue!

**Comment by Phinodel** [comment]
That was it, thank you so much for your help.
I didn't spot that in the docs

Thanks
