### ISSUE TITLE
JSX Runtime issue - React 18, Webpack 5

### ISSUE THREAD

**Issue by szymonkwak** [LouisBrunner/dnd-multi-backend#93]
I am getting a compilation error, similar to the one in this topic: [react-dnd/issues/3418](https://github.com/react-dnd/react-dnd/issues/3418)

```ERROR in ./node_modules/react-dnd-multi-backend/node_modules/react-dnd/dist/esm/core/DndProvider.mjs 28:0-51
Module not found: Error: Package path ./jsx-runtime.js is not exported from package /home/skwak/projects/client/node_modules/react (see exports field in /home/skwak/projects/client/node_modules/react/package.json)
 @ ./node_modules/react-dnd-multi-backend/node_modules/react-dnd/dist/esm/core/index.mjs 2:0-34 2:0-34
 @ ./node_modules/react-dnd-multi-backend/node_modules/react-dnd/dist/esm/index.mjs 2:0-33 2:0-33
 @ ./node_modules/react-dnd-multi-backend/dist/esm/components/DndProvider.js 32:0-60 44:41-57
 @ ./node_modules/react-dnd-multi-backend/dist/esm/index.js 3:0-55 3:0-55
```

Dependencies in the project:
`react 18.2.0`
`webpack: 5.74.0`
**`react-dnd-multi-backend: 7.1.1`**
`react-dnd: 16.0.1`
 `rdndmb-html5-to-touch: 7.1.0`

**Comment by Bibletoon** [comment]
I faced the exactly same issue, [this](https://github.com/react-dnd/react-dnd/issues/3433#issuecomment-1102144912) worked for me. 

Also this fix only works with old api (using DndProvider from react-dnd), using new api causes new error:
```
Uncaught Invariant Violation: Expected drag drop context
    at invariant (http://localhost:3000/static/js/bundle.js:61963:15)
    at useDragDropManager (http://localhost:3000/static/js/bundle.js:66817:66)
    at useDragSourceMonitor (http://localhost:3000/static/js/bundle.js:67043:93)
    at useDrag (http://localhost:3000/static/js/bundle.js:66955:97)
    at CardComponent (http://localhost:3000/static/js/bundle.js:418:71)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:36503:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:40168:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:41636:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:24299:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:24348:20)
```

**Comment by LouisBrunner** [comment]
@Bibletoon Which version of react-dnd are you using?

@szymonkwak  react-dnd v16 is not supported by react-dnd-multi-backend v7 (you should see a peerDependency issue?) so I will tackle this (if not fixed upstream) when I get v8 to build

**Comment by szymonkwak** [comment]
@LouisBrunner I didn't faced peerDependency issue, it's clear now, thank you for the answer.
